---

- name: install memcached
  apt: pkg=memcached state=installed

- name: setting memcached config
  template: >
    src=memcached.conf.j2
    dest=/etc/memcached.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart memcached
