---

- name: create databases
  mysql_db: >
    name=glance
    state=present
    encoding=utf8

- name: database user create
  mysql_user: >
    name=glance
    host={{ item }}
    password={{ mysql_glance_password }}
    priv=glance.*:ALL
  with_items: 
    - '%'
    - 'localhost'

