---

- name: add glance vhost
  rabbitmq_vhost: 
    name=/glance
    state=present

- name: add glance user
  rabbitmq_user:
    user={{ glance_mq_user }}
    password={{ glance_mq_password }}
    vhost=/glance
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present

