---

- name: create databases
  mysql_db: >
    name=cinder
    state=present
    encoding=utf8

- name: database user create
  mysql_user: >
    name=cinder
    host={{ item }}
    password={{ mysql_cinder_password }}
    priv=cinder.*:ALL
  with_items: 
    - '%'
    - 'localhost'

