---

- name: add cinder vhost
  rabbitmq_vhost: 
    name=/cinder
    state=present

- name: add cinder user
  rabbitmq_user:
    user={{ cinder_mq_user }}
    password={{ cinder_mq_password }}
    vhost=/cinder
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present

