---

- name: install horizon use spice
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - openstack-dashboard
   - nova-spiceproxy

#- name: install horizon use novnc
#  apt: >
#    pkg={{ item }}
#    state=installed
#  with_items:
#   - openstack-dashboard
#   - nova-novncproxy

- name: delete ubuntu theme
  apt: >
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
   - openstack-dashboard-ubuntu-theme

- name: setting horizon
  template: >
    src=local_settings.py.j2
    dest=/etc/openstack-dashboard/local_settings.py
    owner=root
    group=root
    mode=0644
  notify:
    - restart horizon use spice

#- name: setting horizon
#  template: >
#    src=local_settings.py.j2
#    dest=/etc/openstack-dashboard/local_settings.py
#    owner=root
#    group=root
#    mode=0644
#  notify:
#    - restart horizon use novnc

