---

- name: install horizon
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - openstack-dashboard
   - nova-novncproxy

- name: setting horizon
  template: >
    src=local_settings.py.j2
    dest=/etc/openstack-dashboard/local_settings.py
    owner=root
    group=root
    mode=0644
  notify:
    - restart horizon

