---

- name: create databases
  mysql_db: >
    name=keystone
    state=present
    encoding=utf8

- name: database user create
  mysql_user: >
    name=keystone
    host={{ item }}
    password={{ mysql_keystone_password }}
    priv=keystone.*:ALL
  with_items: 
    - '%'
    - 'localhost'

