---

- name: install cinder volume
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - "cinder-volume"

- name: setting cinder config for lvm
  template: >
    src=cinder.conf_lvm.j2
    dest=/etc/cinder/cinder.conf
    owner=cinder
    group=cinder
    mode=0644
    backup=yes
  notify:
    - restart cinder volume
  when: cinder_backend == "lvm"

- name: setting cinder config for nfs
  template: >
    src=cinder.conf_nfs.j2
    dest=/etc/cinder/cinder.conf
    owner=cinder
    group=cinder
    mode=0644
    backup=yes
  notify:
    - restart cinder volume
  when: cinder_backend == "nfs"
