---

- name: create databases
  mysql_db: >
    name=nova
    state=present
    encoding=utf8

- name: database user create
  mysql_user: >
    name=nova
    host={{ item }}
    password={{ mysql_nova_password }}
    priv=nova.*:ALL
  with_items: 
    - '%'
    - 'localhost'

