---

- name: add nova vhost
  rabbitmq_vhost: 
    name=/nova
    state=present

- name: add nova user
  rabbitmq_user:
    user={{ nova_mq_user }}
    password={{ nova_mq_password }}
    vhost=/nova
    configure_priv=.*
    read_priv=.*
    write_priv=.*
    state=present

