---

- name: install nova
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - "nova-api"
   - "nova-cert"
   - "nova-conductor"
   - "nova-consoleauth"
   - "nova-objectstore"
   - "nova-scheduler"
   - "python-novaclient"

- name: install nova-network
  apt: >
    pkg=nova-network
    state=installed
  when: network_type == "nova-network"

- name: setting nova config for nova-network
  template: >
    src=nova.conf_nova-network
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0640
    backup=yes
  notify:
    - restart nova control
    - restart nova-network
  when: network_type == "nova-network"

- name: setting nova config for neutron
  template: >
    src=nova.conf_neutron
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0640
    backup=yes
  notify:
    - restart nova control
  when: network_type == "neutron"

- name: nova db sync
  command: /usr/bin/nova-manage db sync
