---

- name: Cmmon Settings
  hosts: all
  sudo: true
  roles:
    - { role: common }

- name: NTP Install
  hosts: all
  sudo: true
  roles:
    - { role: ntp }

- name: RabbitMQ Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: rabbitmq }

- name: MySQL Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: mysql }

- name: Memcached Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: memcached }

- name: Keystone Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: keystone_install }

- name: Keystone Settings
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: keystone_settings }

- name: Glance Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: glance }

- name: OpenStack Image Registry
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: glance_image }

- name: Nova Controller Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: nova_control }

- name: Nova Compute Install
  hosts: all
  sudo: true
  roles:
    - { role: nova_compute }

- name: Horizon Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: horizon }

- name: Cinder Controller Install
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: cinder_control, when: use_cinder == "yes" }

- name: Cinder Volume Install
  #hosts: openstack_volume
  hosts: openstack_ctl
  sudo: true
  roles:
    - { role: cinder_volume, when: use_cinder == "yes" }

#- name: Network Settings
#  hosts: all
#  sudo: true
#  roles:
#    - { role: nova_network }
#    - { role: neutron }

