---

- name: install kvm
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - qemu-kvm
   - libvirt-bin
   - pm-utils
   - vlan
   - virtinst
   - bridge-utils

- name: install nova-compute
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
   - nova-compute-kvm
   - python-novaclient

- name: install nova-network
  apt: >
    pkg=nova-network
    state=installed
  when: network_type == "nova-network"

- name: setting nova config for nova-network
  template: >
    src=nova.conf_nova-network
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0640
    backup=yes
  notify:
    - restart nova-compute
    - restart nova-network
  when: network_type == "nova-network"

- name: setting nova config for neutron
  template: >
    src=nova.conf_neutron
    dest=/etc/nova/nova.conf
    owner=nova
    group=nova
    mode=0640
    backup=yes
  notify:
    - restart nova-compute
  when: network_type == "neutron"


